export const ADMIN_ROUTE = '/admin'
export const CATEGORY_ROUTE = '/category'
export const CREATION_ROUTE = '/creation/resume'
export const STORE_ROUTE = '/store'
export const REGISTRATION_ROUTE = '/registration'
export const AUTHORISATION_ROUTE = '/authorisation'
export const AREA_ROUTE = '/personal/area'