# Generated by Django 4.0.5 on 2022-07-04 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_remove_myuser_username_alter_myuser_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='user_name',
        ),
    ]
