# Generated by Django 4.0.5 on 2022-07-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_remove_myuser_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='gender',
        ),
        migrations.AddField(
            model_name='myuser',
            name='facebook',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Link on Facebook'),
        ),
    ]
