# Generated by Django 3.2.14 on 2022-07-09 14:59

import custom_user.services
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_remove_myuser_gender_myuser_facebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=custom_user.services.get_path_upload_avatar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg']), custom_user.services.validate_size_image], verbose_name='Avatar'),
        ),
    ]
