# Generated by Django 3.2.14 on 2022-07-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0006_alter_myuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First login'),
        ),
    ]
