# Generated by Django 3.2.14 on 2022-07-11 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0008_alter_myuser_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='phone',
        ),
    ]
