# Generated by Django 3.2.14 on 2022-07-11 12:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import resume.services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=350, verbose_name='Name')),
                ('start_date', models.DateTimeField(blank=True, verbose_name='Start date')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='End date')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=350, verbose_name='Name')),
                ('about', models.TextField(blank=True, verbose_name='About')),
                ('start_date', models.DateTimeField(blank=True, verbose_name='Start date')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='End date')),
            ],
            options={
                'verbose_name': 'Employment History',
                'verbose_name_plural': 'Employment Histories',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='Name')),
                ('about', models.TextField(blank=True, verbose_name='About')),
                ('start_date', models.DateTimeField(blank=True, verbose_name='Start date')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='End date')),
            ],
            options={
                'verbose_name': 'Employment History',
                'verbose_name_plural': 'Employment Histories',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('skill', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, max_length=1, verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='Name')),
                ('skill', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, max_length=1, verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Link name')),
                ('link', models.URLField(blank=True, max_length=300, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Last name')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Middle name')),
                ('phone', models.CharField(blank=True, max_length=14, verbose_name='Phone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=resume.services.get_path_upload_photo, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), resume.services.validate_size_image], verbose_name='Photo')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Country')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='City')),
                ('additional_address_info', models.TextField(blank=True, max_length=500, verbose_name='Additional address info')),
                ('date_of_birth', models.DateField(blank=True, verbose_name='Date of Birth')),
                ('vacancy', models.CharField(blank=True, max_length=250, verbose_name='Vacancy')),
                ('about_me', models.TextField(blank=True, verbose_name='About me')),
                ('hobbies', models.TextField(blank=True, verbose_name='Hobbies')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_resumes', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('courses', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume_courses', to='resume.courses', verbose_name='Courses')),
                ('education', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume_education', to='resume.education', verbose_name='Education')),
                ('employment_history', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume_employment', to='resume.employmenthistory', verbose_name='Employment History')),
                ('languages', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume_languages', to='resume.languages', verbose_name='Languages')),
                ('skills', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume_skills', to='resume.skills', verbose_name='Skills')),
                ('social_links', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume_links', to='resume.sociallink', verbose_name='Social Links')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'ordering': ['-id'],
            },
        ),
    ]
