# Generated by Django 3.2.14 on 2022-07-11 17:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import resume.services


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0002_auto_20220711_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Last name')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Middle name')),
                ('phone', models.CharField(blank=True, max_length=14, verbose_name='Phone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=resume.services.get_path_upload_photo, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), resume.services.validate_size_image], verbose_name='Photo')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Country')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='City')),
                ('additional_address_info', models.TextField(blank=True, max_length=500, verbose_name='Additional address info')),
                ('date_of_birth', models.DateField(blank=True, verbose_name='Date of Birth')),
                ('vacancy', models.CharField(blank=True, max_length=250, verbose_name='Vacancy')),
                ('about_me', models.TextField(blank=True, verbose_name='About me')),
                ('hobbies', models.TextField(blank=True, verbose_name='Hobbies')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_main_info', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-id'], 'verbose_name': 'Education', 'verbose_name_plural': 'Educations'},
        ),
        migrations.RemoveField(
            model_name='courses',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='education',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='employmenthistory',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='languages',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='resume',
        ),
        migrations.AddField(
            model_name='courses',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_education', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_employment', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='languages',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_languages', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='skills',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
