# Generated by Django 3.2.14 on 2022-07-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20220711_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maininfo',
            options={'ordering': ['-id'], 'verbose_name': 'Main Info', 'verbose_name_plural': 'Main Info'},
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, max_length=1, verbose_name='Skill'),
        ),
    ]
