# Generated by Django 3.2.14 on 2022-07-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_languages_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='end_date',
            field=models.DateField(blank=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='start_date',
            field=models.DateField(blank=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(blank=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='end_date',
            field=models.DateField(blank=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='start_date',
            field=models.DateField(blank=True, verbose_name='Start date'),
        ),
    ]
