# Generated by Django 3.2.14 on 2022-07-12 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import resume.services


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0009_alter_maininfo_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=resume.services.get_path_upload_pdf, verbose_name='Resume PDF File')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pdf', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
