# Generated by Django 3.2.14 on 2022-07-13 10:54

import django.core.validators
from django.db import migrations, models
import resume.services


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_resumepdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumepdf',
            options={'ordering': ['-id'], 'verbose_name': 'User PDF file', 'verbose_name_plural': 'User PDF files'},
        ),
        migrations.AlterField(
            model_name='languages',
            name='skill',
            field=models.CharField(choices=[('novice', 'novice'), ('beginner', 'beginner'), ('skillful', 'skillful'), ('experienced', 'experienced'), ('expert', 'expert')], default=1, max_length=25, verbose_name='Skill'),
        ),
        migrations.AlterField(
            model_name='resumepdf',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=resume.services.get_path_upload_pdf, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Resume PDF File'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill',
            field=models.CharField(choices=[('novice', 'novice'), ('beginner', 'beginner'), ('skillful', 'skillful'), ('experienced', 'experienced'), ('expert', 'expert')], default=1, max_length=25, verbose_name='Skill'),
        ),
    ]
