# Generated by Django 3.2.14 on 2022-07-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_auto_20220713_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmenthistory',
            name='name',
        ),
        migrations.AddField(
            model_name='courses',
            name='company',
            field=models.CharField(blank=True, max_length=250, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='education',
            name='institution',
            field=models.CharField(blank=True, max_length=200, verbose_name='Institution'),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='company',
            field=models.CharField(blank=True, max_length=250, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='vacancy',
            field=models.CharField(blank=True, max_length=250, verbose_name='Vacancy'),
        ),
    ]
